config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard'
  devise_for :users

  resources :plants do
    resources :bookings, only: [ :new, :create]
  end
  resources :bookings, only: [ :edit, :update, :show ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :plant
  belongs_to :user

  validates :start_date, :end_date, presence: true
  validates :status, inclusion: { in: ["Waiting", "Accepted", "Declined"] }

  before_save :set_total_price

  def set_total_price
    totalprice = plant.price * (end_date - start_date).to_i
  end
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :price, presence: true, numericality: true

  has_many_attached :photos

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true

  has_one_attached :avatar

  has_many :bookings
  has_many :plants, through: :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :authenticate_user!
  include Pundit
  before_action :configure_permitted_parameters, if: :devise_controller?

    # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not Authorized to Perform this action"
    redirect_to(root_path)
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]

  def new
    @plant = Plant.find(params[:plant_id])
    @booking = Booking.new
    authorize(@plant)
  end

  def create
    @booking = Booking.new(booking_params)
    authorize(@booking)
    @plant = Plant.find(params[:plant_id])
    @booking.plant = @plant
    @booking.user = current_user

    if @booking.save
      redirect_to booking_path(@booking)
    else
      @plant = Plant.find(params[:plant_id])
      render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @plant = @booking.plant
    @booking.update(booking_params)
    redirect_to booking_path(@booking)
  end

  def show
    @booking = Booking.find(params[:id])
    @plant = @booking.plant
    @booking.user = current_user
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status, :totalprice)
  end

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @plants = Plant.all
    # @plant = Plant.where()
  end

  def dashboard
    @user = current_user
    @plants = Plant.where(user: @user)
    @my_plant_bookings = Booking.joins(:plant).where(plant: { user: @user })
    @my_bookings = Booking.where(user: @user)
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: %i[ show edit update destroy ]

  def index
    @plants = policy_scope(Plant)

    @plant = Plant.new

    if params[:query].present?
      sql_query = "name ILIKE :query OR description ILIKE :query OR address ILIKE :query"
      @plants = @plants.where(sql_query, query: "%#{params[:query]}%")
    end

    if params[:address].present?
      @plants = @plants.near(params[:address], params[:km].present? ? params[:km] : 10)
    end

    @markers = @plants.geocoded.map do |plant|
      {
        lat: plant.latitude,
        lng: plant.longitude,
        info_window: render_to_string(partial: "info_window", locals: { plant: plant })
      }
    end
  end

  def new
    @plant = Plant.new
    authorize @plant
  end

  def show
    @plant = Plant.find(params[:id])
  end

  def create
    @plants = policy_scope(Plant)
    @plant = Plant.new(plant_params)
    authorize @plant
    @plant.user = current_user
    if @plant.save
      redirect_to plant_path(@plant)
    else
      render "plants/index"
    end
  end

  def edit
    @plant = Plant.find(params[:id])
  end

  def update
    @plant = Plant.find(params[:id])
    @plant.update(plant_params)
    redirect_to plant_path(@plant)
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy
    # no need for app/views/plants/destroy.html.erb
    redirect_to plants_path
  end

  private

  def set_plant
    @plant = Plant.find(params[:id])
    authorize @plant
  end

  def plant_params
    params.require(:plant).permit(:name, :address, :description, :availability, :price, photos: [])
  end
end

  # <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @article.photo.key, height: 300, crop: :fill %>')">
  #   Cool article
  # </div>

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<%= simple_form_for [ @plant, @booking ] do |f| %>
  <%= f.input :start_date, as: :date %>
  <%= f.input :end_date, as: :date %>
  <%= f.input :status%>
  <%= f.submit "Update booking", class: "btn btn-primary" %>
<% end %>

app/views/bookings/new.html.erb
<div class="form-container">
  <div class="row">
    <div class="container py-5 col-4">
      <div class="mb-3 bg-white">
        <%= simple_form_for [ @plant, @booking ] do |f| %>
          <%= f.input :start_date, as: :date %>
          <%= f.input :end_date, as: :date %>
          <%= f.input :status%>
          <%= f.submit "Submit booking", class: "btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="show-plant min-h-container">
  <% if @booking.plant.user != current_user %>
    <h2 class="titre-section text-center mb-1 mt-2">Your Booking</h2>

    <div class="cont-plant">
      <article class="article-plant mt-5" style="width: 50%">
        <p>Dear Jean, you have just booked Saskia's <strong><%= @plant.name %></strong>, from <strong><%= @booking.start_date.strftime('%d-%m-%Y') %></strong> to <strong><%= @booking.end_date.strftime('%d-%m-%Y') %></strong>.</p>

        <% if @booking.status == "Waiting" %>
          <p>Please wait for the owner's confirmation.</p>
        <% else %>
          <p>The booking status is: <span class="foot"><strong><%= @booking.status%><strong></span></p>
        <% end %>

        <p><U>Booking details</U>:</p>
        <p>Total price: <%= @booking.set_total_price %>€</p>
        <p>Plant location: <%= @plant.address %> </p>
        <p><i class="fas fa-seedling mr-2"></i> <%= link_to " Back to plants", plants_path %></p>

        <% if @booking.plant.user == current_user %>
          <%= simple_form_for @booking do |f| %>
            <%= f.input :status, as: :hidden, input_html: { value: 'Accepted' } %>
            <%= f.submit "Accept"%>
          <% end %>
          <%= simple_form_for @booking do |f| %>
            <%= f.input :status, as: :hidden, input_html: { value: 'Declined' } %>
            <%= f.submit "Decline"%>
          <% end %>
        <% else %>
        <% end %>
      </article>
      <%= cl_image_tag @plant.photos.first.key,class:"mt-5", height: 200, width: 300, crop: :fill %>
    </div>


  <% else %>
    <h2 class="titre-section text-center mb-4">Manage booking</h2>
    <div class="cont-plant">
      <article class="article-plant mt-2" style="width">
        <p>You have a pending booking for the <strong><%= @plant.name %></strong> plant, from <strong><%= @booking.start_date.strftime('%d/%m/%Y') %></strong> to <strong><%= @booking.end_date.strftime('%d/%m/%Y') %></strong>.</p>


        <% if @booking.status == "Waiting" %>
          <p>Waiting for your confirmation, please accept or decline the booking.</p>
          <% if @booking.plant.user == current_user %>
            <div class='d-flex'>
              <%= simple_form_for @booking do |f| %>
                <%= f.input :status, as: :hidden, input_html: { value: 'Accepted' } %>
                <%= f.submit "Accept", class:"mr-2 btn-success" %>
              <% end %>
                <%= simple_form_for @booking do |f| %>
                <%= f.input :status, as: :hidden, input_html: { value: 'Declined' } %>
                <%= f.submit "Decline", class:"btn-warning" %>
              <% end %>
            </div>
          <% end %>
        <% else %>
          <p>The booking status is: <%= @booking.status %></p>
        <% end %>

        <p class="mt-4"><U>Booking details</U>:</p>
        <p>Total price: <%= @booking.set_total_price %>€</p>
        <p>Plant location: <%= @plant.address %> </p>
        <p><i class="fas fa-seedling mr-2"></i> <%= link_to " Back to dashboard", dashboard_path %></p>


      </article>
      <%= cl_image_tag @plant.photos.first.key, class:"image-plant mt-5", height: 200, width: 300, crop: :fill %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GreenNb</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Courgette&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Pattaya&family=Sansita+Swashed&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@400;500&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;600&display=swap" rel="stylesheet">
    <link rel="icon" type="logo" href="<%= image_url("log.png") %>">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class='global-container'>
      <%= yield %>
    </div>
    <%= render 'shared/flashes' %>
    <%= render 'shared/footer' %>

  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="form-container">
  <h2 class="titre-section text-center mb-4 pt-4">Dashboard</h2>
  <div class="dashboard-boxes">

    <div class="dash-profil-plant-box" style="width: 100%">
      <div class="dash-box profil">
        <h3 class="titre-section small-title mt-2 mb-4">Manage my bookings</h3>
        <h4>
          <i class="fas fa-seedling mr-2"></i>My booked plants
          (<span class="<%= 'red' if @my_plant_bookings.length > 0 %>"><%= @my_plant_bookings.length%></span>)
        </h4>
        <ul>
        <% @my_plant_bookings.each do |booking| %>
          <li>
            <%= link_to booking.plant.name, booking_path(booking) %>
          </li>
        <% end %>
        </ul>
        <h4>
          <i class="fas fa-seedling mr-2"></i> My bookings
            (<span class="<%= 'red' if @user.bookings.length > 0 %>"><%= @user.bookings.length %></span>)
        </h4>
        <ul>
          <% @my_bookings.each do |booking| %>
          <li>
            <%= link_to booking.plant.name, booking_path(booking) %>
          </li>
        <% end %>
        </ul>
      </div>


      <div class="dash-box plants">
        <h3 class="titre-section small-title mt-2 mb-4">My Plants</h3>
        <%= link_to new_plant_path(@plant) do %>
          <h4 class="strong-a mb-4"><i class="fas fa-seedling mr-2"></i> + Add a plant</h4>
        <% end  %>
        <ul>
        <% @plants.each do |plant| %>
        <li class="mb-3">
          <%= cl_image_tag plant.photos.first.key, height: 40, width: 40, crop: :fill, class: "avatar mr-2" %>
          <%= link_to "#{plant.name.split.map(&:capitalize).join(' ')}", plant_path(plant) %>
          • <%= link_to edit_plant_path(plant) do %>
            <i class="fas fa-pen ml-2 mr-2"></i>
          <% end  %>
          <%= link_to plant_path(plant), method: :delete, data: { confirm: "Are you sure ?"} do %>
          <i class="far fa-trash-alt"></i>
          <% end  %>
          <%# <i class="fas fa-seedling"></i> %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>


    <div class="dash-box manage">
      <div class="photo-profil">
        <h3 class="titre-section small-title mt-2 mb-4">My Profile</h3>
        <%= cl_image_tag current_user.avatar.key, class:"avatar mt-2 mb-4" %>
      </div>
      <a class="btn btn-success mb-2" href="">Edit profile <i class="fas fa-pen ml-2"></i></a>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="small-container">
    <h4><a href="" class="link-home">About us</a></h4>
    <h1>greenNb</h1>
    <h4><a href="" class="link-home">Our Engagement</a></h4>
</div>

<div class="img-accueil">
  <h2>RENT A PLANT TO MAKE YOUR INTERIOR GREAT AGAIN</h2>
  <hr class="ligne">
  <h3>Cultivate well-being in your apartment <br>without having a green thumb</h3>
  <a class="btn btn-success btn-rent pt-2" href="plants">
      Rent a Plant
  </a>
</div>

<div class="p-4">
<%= render 'plants/cards_grid', plants: @plants %>
</div>

app/views/plants/_cards_grid.html.erb
<div class="display-plants mt-4">
  <div class="row">
    <% plants.each do |plant| %>
      <div class="col-sm-4" >
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= "https://res.cloudinary.com/db0v28ezw/image/upload/v1621437963/#{plant.photos.first.key}.jpg" %>');">
          <div class="card-description">
            <p><strong><%= plant.name.capitalize %></strong></p>
          </div>
          <div class="see-this-plant">
            <%= link_to "See this Plant", plant_path(plant) %>
            <i class="fas fa-seedling fa-index"></i>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>


      <%# <% if @plant.user != current_user %>
        <%# <p><%= link_to "Book this plant", new_plant_booking_path(@plant)%></p>
      <%# <% end %>

app/views/plants/_form.html.erb
      <%= simple_form_for @plant do |f| %>
        <%= f.input :name, placeholder: 'Dahlia' %>
        <%= f.input :description, placeholder: 'My plant will make your home green again' %>
        <%= f.input :address, placeholder: 'Rentres l adresse de ta plante ! ! !' %>
        <%= f.input :availability, as: :select, include_blank: false, collection: ['no','yes'] %>
        <%= f.input :price, placeholder: 'price per day' %>
        <%= f.input :photos, as: :file, label: "Picture of your plant:", input_html: { multiple: true } %>

        <% button_text = @plant.new_record? ? "Add my plant" : "Edit my plant" %>
        <%= f.submit button_text, class: "btn btn-success border mt-3" %>
      <% end%>

app/views/plants/_info_window.html.erb
<h4><%= plant.name %></h4>
<p><%= plant.address %></p>

app/views/plants/edit.html.erb
<div class="form-container">
  <div class="row">
    <div class="container py-5 col-4">
      <div class="mb-3 bg-white">
        <h2 class="titre-section">Edit my plant</h2>
        <%= render "form", plant: @plant %>
      </div>
    </div>
  </div>
</div>

app/views/plants/index.html.erb
<h2 class="titre-section text-center mt-4 mb-5">Find the plant of your dream</h2>

<div class="container search">
  <div class="search-duo mb-4">
  <%= form_tag plants_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "barre-recherche",
      placeholder: "Find your best plant"
    %>

    <%= text_field_tag :address,
      params[:address],
      class: "barre-recherche",
      placeholder: "Enter an address"
    %>

    <%= text_field_tag :km,
      params[:km],
      class: "barre-recherche",
      placeholder: "How many km around ?"
    %>
    <%= submit_tag "Search", class: "btn-search" %>
  <% end %>
  </div>
</div>

<div class="main-container">
  <div class="display-cards m-4">
    <%= render "cards_grid", plants: @plants %>
  </div>

  <div id="map" class="mt-5 mr-4"
    style="width: 40%; height: 100vh;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/plants/new.html.erb
<div class="form-container">
  <div class="row">
    <div class="container py-5 col-4">
      <div class="mb-3 bg-white">
        <h2 class="titre-section">Create my plant</h2>
        <%= render "form", plant: @plant %>
      </div>
    </div>
  </div>
</div>

app/views/plants/show.html.erb
    <div class="show-plant min-h-container">
      <h2 class="titre-section text-center mb-4"><%= @plant.name.capitalize %></h2>
      <div class="cont-plant">
        <article class="article-plant mt-5">

          <div>
            <% if Booking.where(plant_id: @plant.id).count > 0 && @plant.user == current_user %>
              <p>Status : Booked <i class="fas fa-check"></i></p>
            <% end %>
            <p><%= @plant.description %></p>
            <p><%= @plant.price %>€ / day</p>
          </div>
          <div>
            <% if @plant.user != @current_user %>
              <p><%= link_to "Book this plant", new_plant_booking_path(@plant), class:"btn btn-success" %></p>
            <% else %>
              <p><%= link_to "Edit my plant", edit_plant_path(@plant) %><i class="fas fa-pen ml-2 mr-2"></i></p>
              <p><%= link_to "Delete my plant", plant_path(@plant), method: :delete, data: { confirm: "Are you sure ?"} %> <i class="far fa-trash-alt"></i></p>
            <% end %>

            <p><i class="fas fa-seedling mr-2"></i> <%= link_to " Back to plants", plants_path %></p>
        </article>

        <div>
          <div id="carouselExampleControls" class="carousel mt-5 mb-5" data-ride="carousel">
            <div class="carousel-inner">
              <% @plant.photos.each_with_index do |photo, i| %>
                <div class="carousel-item <%= 'active' if i == 0 %> ">
                  <%= cl_image_tag photo.key, class:"d-block", height: 300, width: 400, crop: :fill %>
                </div>
              <% end %>
            </div>

              <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>

        </div>
      </div>
    </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <p class="mt-3 foot">Join the green gang</p>
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at greenNb
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "growth.png"%>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Bookings", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Profile", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>